{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "coredns-autoscaler.fullname" . }}
  labels:
    {{- include "coredns-autoscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "coredns-autoscaler.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "coredns-autoscaler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
