apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coredns-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coredns-autoscaler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "coredns-autoscaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coredns-autoscaler.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "coredns-autoscaler.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: autoscaler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /cluster-proportional-autoscaler
            - --namespace={{ .Release.Namespace }}
            - --configmap={{ include "coredns-autoscaler.configMapName" . }}
            - --target={{ .Values.target.ref }}
            - --poll-period-seconds={{ .Values.pollPeriodSeconds }}
            - --logtostderr=true
            - --v={{ .Values.logLevel }}
            - {{ printf "--default-params={%q:%s}" (include "coredns-autoscaler.paramsKey" .) (include "coredns-autoscaler.params" .) | quote }}
            {{- with .Values.nodeLabels }}
            - --nodelabels={{ . }}
            {{- end }}
            {{- range .Values.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
